# coding: utf-8

"""
    Patch API V1

    The core API used to integrate with Patch's service  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: developers@usepatch.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import patch_api
from patch_api.api.photos_api import PhotosApi  # noqa: E501
from patch_api.rest import ApiException


class TestPhotosApi(unittest.TestCase):
    """PhotosApi unit test stubs"""

    def setUp(self):
        self.api = patch_api.api.photos_api.PhotosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_photo(self):
        """Test case for delete_photo

        Deletes a photo for the project  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
