# coding: utf-8

"""
    Patch API V1

    The core API used to integrate with Patch's service  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: developers@usepatch.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import patch_api
from patch_api.api.orders_api import OrdersApi  # noqa: E501
from patch_api.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = patch_api.api.orders_api.OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_order(self):
        """Test case for cancel_order

        Cancel an order  # noqa: E501
        """
        pass

    def test_create_order(self):
        """Test case for create_order

        Creates an order  # noqa: E501
        """
        pass

    def test_place_order(self):
        """Test case for place_order

        Place an order  # noqa: E501
        """
        pass

    def test_retrieve_order(self):
        """Test case for retrieve_order

        Retrieves an order  # noqa: E501
        """
        pass

    def test_retrieve_orders(self):
        """Test case for retrieve_orders

        Retrieves a list of orders  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
