# coding: utf-8

"""
    Patch API V1

    The core API used to integrate with Patch's service  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: developers@usepatch.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import os

import patch_api
from patch_api.api.orders_api import OrdersApi  # noqa: E501
from patch_api.models.create_order_request import CreateOrderRequest
from patch_api.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        configuration = patch_api.Configuration(api_key=os.environ.get('SANDBOX_API_KEY'))
        api_client = patch_api.ApiClient(configuration)
        self.api = OrdersApi(api_client=api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_interactions_with_an_order(self):
        """Test case for create_order, retrieve_order, cancel_order
        """

        """Create an order
        """
        create_order_request = CreateOrderRequest(mass_g=100)
        order = self.api.create_order(create_order_request)

        self.assertTrue(order)

        """Retrieve an order
        """
        create_order_request = CreateOrderRequest(mass_g=100)
        order = self.api.create_order(create_order_request=create_order_request)
        retrieved_order = self.api.retrieve_order(id=order.data.id)

        self.assertTrue(retrieved_order)

        """Cancel an order
        """
        cancelled_order = self.api.retrieve_order(id=order.data.id)

        self.assertTrue(cancelled_order)


    def test_retrieve_orders(self):
        """Test case for retrieve_orders

        Retrieves a list of orders  # noqa: E501
        """
        orders = self.api.retrieve_orders()
        self.assertTrue(isinstance(orders.data, list))


if __name__ == '__main__':
    unittest.main()
