# coding: utf-8

"""
    Patch API V1

    The core API used to integrate with Patch's service  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: developers@usepatch.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import patch_api
from patch_api.models.create_project_request import CreateProjectRequest  # noqa: E501
from patch_api.rest import ApiException

class TestCreateProjectRequest(unittest.TestCase):
    """CreateProjectRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateProjectRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = patch_api.models.create_project_request.CreateProjectRequest()  # noqa: E501
        if include_optional :
            return CreateProjectRequest(
                name = '0',
                description = '0',
                country = 'TJ',
                state = '0',
                verifier = '0',
                type = 'biomass',
                standard_type = 'american_carbon_registry',
                longitude = '0',
                latitude = '0',
                production = '0',
                organization_id = '0'
            )
        else :
            return CreateProjectRequest(
        )

    def testCreateProjectRequest(self):
        """Test CreateProjectRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

        self.assertTrue(inst_req_only)
        self.assertTrue(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
