repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: name-tests-test
# Note: temporary disabling to commit temporary work. Re-enable before merging.
# -   repo: https://github.com/pycqa/flake8
#     rev: '4.0.1'
#     hooks:
#     - id: flake8
#       args: ['--config=.flake8']
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    - id: black
