# coding: utf-8

"""
    Patch API V1

    The core API used to integrate with Patch's service  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: developers@usepatch.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from patch_api.configuration import Configuration


class Standard(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"type": "str", "acronym": "str", "description": "str"}

    attribute_map = {"type": "type", "acronym": "acronym", "description": "description"}

    def __init__(
        self, type=None, acronym=None, description=None, local_vars_configuration=None
    ):  # noqa: E501
        """Standard - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._acronym = None
        self._description = None
        self.discriminator = None

        self.type = type
        self.acronym = acronym
        self.description = description

    @property
    def type(self):
        """Gets the type of this Standard.  # noqa: E501

        The standard type.  # noqa: E501

        :return: The type of this Standard.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Standard.

        The standard type.  # noqa: E501

        :param type: The type of this Standard.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation and type is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `type`, must not be `None`"
            )  # noqa: E501

        self._type = type

    @property
    def acronym(self):
        """Gets the acronym of this Standard.  # noqa: E501

        The acronym for the standard.  # noqa: E501

        :return: The acronym of this Standard.  # noqa: E501
        :rtype: str
        """
        return self._acronym

    @acronym.setter
    def acronym(self, acronym):
        """Sets the acronym of this Standard.

        The acronym for the standard.  # noqa: E501

        :param acronym: The acronym of this Standard.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation and acronym is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `acronym`, must not be `None`"
            )  # noqa: E501

        self._acronym = acronym

    @property
    def description(self):
        """Gets the description of this Standard.  # noqa: E501

        The description of the standard.  # noqa: E501

        :return: The description of this Standard.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Standard.

        The description of the standard.  # noqa: E501

        :param description: The description of this Standard.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation and description is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `description`, must not be `None`"
            )  # noqa: E501

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Standard):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Standard):
            return True

        return self.to_dict() != other.to_dict()
