name: Health check
on:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        python: ['3.10']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Run tests
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        run: make test

      - name: Notify slack
        if: failure()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: eng-notifications
