name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
      - uses: psf/black@stable
        with:
          version: "24.10.0"

  build-and-test:
    runs-on: ubuntu-latest
    name: Python Library tests
    steps:
      - name: Check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: "3.8"

      - name: Run tests
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        run: make test
